/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Id = IDL.Nat;
export const EnrollmentInput = IDL.Record({ 'studentId' : Id, 'classId' : Id });
export const Timestamp = IDL.Int;
export const Enrollment = IDL.Record({
  'id' : Id,
  'studentId' : Id,
  'classId' : Id,
  'enrolledAt' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClassInput = IDL.Record({
  'name' : IDL.Text,
  'homeroomTeacherId' : IDL.Opt(Id),
  'gradeLevel' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const Class = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'homeroomTeacherId' : IDL.Opt(Id),
  'updatedAt' : Timestamp,
  'gradeLevel' : IDL.Text,
  'capacity' : IDL.Nat,
  'enrolledCount' : IDL.Nat,
});
export const StudentStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'transferred' : IDL.Null,
  'graduated' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const StudentInput = IDL.Record({
  'status' : StudentStatus,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'guardianPhone' : IDL.Text,
  'gender' : Gender,
  'guardianName' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : Id,
  'status' : StudentStatus,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'guardianPhone' : IDL.Text,
  'updatedAt' : Timestamp,
  'gender' : Gender,
  'guardianName' : IDL.Text,
  'classIds' : IDL.Vec(Id),
});
export const TeacherInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : Id,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'phone' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ClassDistribution = IDL.Record({
  'classId' : Id,
  'className' : IDL.Text,
  'studentCount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'studentsPerClass' : IDL.Vec(ClassDistribution),
  'teacherCount' : IDL.Nat,
  'classCount' : IDL.Nat,
  'studentCount' : IDL.Nat,
  'enrollmentCount' : IDL.Nat,
});
export const ActivityKind = IDL.Variant({
  'teacherCreated' : IDL.Null,
  'teacherDeleted' : IDL.Null,
  'enrollmentRemoved' : IDL.Null,
  'studentUpdated' : IDL.Null,
  'classUpdated' : IDL.Null,
  'teacherUpdated' : IDL.Null,
  'studentCreated' : IDL.Null,
  'studentDeleted' : IDL.Null,
  'enrollmentAdded' : IDL.Null,
  'classCreated' : IDL.Null,
  'classDeleted' : IDL.Null,
});
export const ActivityEntry = IDL.Record({
  'at' : Timestamp,
  'id' : Id,
  'kind' : ActivityKind,
  'message' : IDL.Text,
  'performedBy' : IDL.Principal,
});
export const ClassFilter = IDL.Record({
  'search' : IDL.Opt(IDL.Text),
  'homeroomTeacherId' : IDL.Opt(Id),
});
export const EnrollmentFilter = IDL.Record({
  'studentId' : IDL.Opt(Id),
  'classId' : IDL.Opt(Id),
});
export const StudentFilter = IDL.Record({
  'status' : IDL.Opt(StudentStatus),
  'search' : IDL.Opt(IDL.Text),
  'classId' : IDL.Opt(Id),
});
export const TeacherFilter = IDL.Record({ 'search' : IDL.Opt(IDL.Text) });
export const ClassUpdate = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'homeroomTeacherId' : IDL.Opt(Id),
  'gradeLevel' : IDL.Opt(IDL.Text),
  'capacity' : IDL.Opt(IDL.Nat),
});
export const StudentUpdate = IDL.Record({
  'status' : IDL.Opt(StudentStatus),
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'guardianPhone' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
  'guardianName' : IDL.Opt(IDL.Text),
});
export const TeacherUpdate = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addEnrollment' : IDL.Func([EnrollmentInput], [Enrollment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([ClassInput], [Class], []),
  'createStudent' : IDL.Func([StudentInput], [Student], []),
  'createTeacher' : IDL.Func([TeacherInput], [Teacher], []),
  'deleteClass' : IDL.Func([Id], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([Id], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([Id], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([Id], [IDL.Opt(Class)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getRecentActivity' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getStudent' : IDL.Func([Id], [IDL.Opt(Student)], ['query']),
  'getTeacher' : IDL.Func([Id], [IDL.Opt(Teacher)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listClasses' : IDL.Func([ClassFilter], [IDL.Vec(Class)], ['query']),
  'listEnrollments' : IDL.Func(
      [EnrollmentFilter],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'listStudents' : IDL.Func([StudentFilter], [IDL.Vec(Student)], ['query']),
  'listTeachers' : IDL.Func([TeacherFilter], [IDL.Vec(Teacher)], ['query']),
  'removeEnrollment' : IDL.Func([Id], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateClass' : IDL.Func([Id, ClassUpdate], [IDL.Opt(Class)], []),
  'updateStudent' : IDL.Func([Id, StudentUpdate], [IDL.Opt(Student)], []),
  'updateTeacher' : IDL.Func([Id, TeacherUpdate], [IDL.Opt(Teacher)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Id = IDL.Nat;
  const EnrollmentInput = IDL.Record({ 'studentId' : Id, 'classId' : Id });
  const Timestamp = IDL.Int;
  const Enrollment = IDL.Record({
    'id' : Id,
    'studentId' : Id,
    'classId' : Id,
    'enrolledAt' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClassInput = IDL.Record({
    'name' : IDL.Text,
    'homeroomTeacherId' : IDL.Opt(Id),
    'gradeLevel' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const Class = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'homeroomTeacherId' : IDL.Opt(Id),
    'updatedAt' : Timestamp,
    'gradeLevel' : IDL.Text,
    'capacity' : IDL.Nat,
    'enrolledCount' : IDL.Nat,
  });
  const StudentStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'transferred' : IDL.Null,
    'graduated' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const StudentInput = IDL.Record({
    'status' : StudentStatus,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'guardianPhone' : IDL.Text,
    'gender' : Gender,
    'guardianName' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : Id,
    'status' : StudentStatus,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'guardianPhone' : IDL.Text,
    'updatedAt' : Timestamp,
    'gender' : Gender,
    'guardianName' : IDL.Text,
    'classIds' : IDL.Vec(Id),
  });
  const TeacherInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : Id,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'phone' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ClassDistribution = IDL.Record({
    'classId' : Id,
    'className' : IDL.Text,
    'studentCount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'studentsPerClass' : IDL.Vec(ClassDistribution),
    'teacherCount' : IDL.Nat,
    'classCount' : IDL.Nat,
    'studentCount' : IDL.Nat,
    'enrollmentCount' : IDL.Nat,
  });
  const ActivityKind = IDL.Variant({
    'teacherCreated' : IDL.Null,
    'teacherDeleted' : IDL.Null,
    'enrollmentRemoved' : IDL.Null,
    'studentUpdated' : IDL.Null,
    'classUpdated' : IDL.Null,
    'teacherUpdated' : IDL.Null,
    'studentCreated' : IDL.Null,
    'studentDeleted' : IDL.Null,
    'enrollmentAdded' : IDL.Null,
    'classCreated' : IDL.Null,
    'classDeleted' : IDL.Null,
  });
  const ActivityEntry = IDL.Record({
    'at' : Timestamp,
    'id' : Id,
    'kind' : ActivityKind,
    'message' : IDL.Text,
    'performedBy' : IDL.Principal,
  });
  const ClassFilter = IDL.Record({
    'search' : IDL.Opt(IDL.Text),
    'homeroomTeacherId' : IDL.Opt(Id),
  });
  const EnrollmentFilter = IDL.Record({
    'studentId' : IDL.Opt(Id),
    'classId' : IDL.Opt(Id),
  });
  const StudentFilter = IDL.Record({
    'status' : IDL.Opt(StudentStatus),
    'search' : IDL.Opt(IDL.Text),
    'classId' : IDL.Opt(Id),
  });
  const TeacherFilter = IDL.Record({ 'search' : IDL.Opt(IDL.Text) });
  const ClassUpdate = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'homeroomTeacherId' : IDL.Opt(Id),
    'gradeLevel' : IDL.Opt(IDL.Text),
    'capacity' : IDL.Opt(IDL.Nat),
  });
  const StudentUpdate = IDL.Record({
    'status' : IDL.Opt(StudentStatus),
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'guardianPhone' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
    'guardianName' : IDL.Opt(IDL.Text),
  });
  const TeacherUpdate = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addEnrollment' : IDL.Func([EnrollmentInput], [Enrollment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([ClassInput], [Class], []),
    'createStudent' : IDL.Func([StudentInput], [Student], []),
    'createTeacher' : IDL.Func([TeacherInput], [Teacher], []),
    'deleteClass' : IDL.Func([Id], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([Id], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([Id], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([Id], [IDL.Opt(Class)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getRecentActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getStudent' : IDL.Func([Id], [IDL.Opt(Student)], ['query']),
    'getTeacher' : IDL.Func([Id], [IDL.Opt(Teacher)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listClasses' : IDL.Func([ClassFilter], [IDL.Vec(Class)], ['query']),
    'listEnrollments' : IDL.Func(
        [EnrollmentFilter],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'listStudents' : IDL.Func([StudentFilter], [IDL.Vec(Student)], ['query']),
    'listTeachers' : IDL.Func([TeacherFilter], [IDL.Vec(Teacher)], ['query']),
    'removeEnrollment' : IDL.Func([Id], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateClass' : IDL.Func([Id, ClassUpdate], [IDL.Opt(Class)], []),
    'updateStudent' : IDL.Func([Id, StudentUpdate], [IDL.Opt(Student)], []),
    'updateTeacher' : IDL.Func([Id, TeacherUpdate], [IDL.Opt(Teacher)], []),
  });
};

export const init = ({ IDL }) => { return []; };