/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'at' : Timestamp,
  'id' : Id,
  'kind' : ActivityKind,
  'message' : string,
  'performedBy' : Principal,
}
export type ActivityKind = { 'teacherCreated' : null } |
  { 'teacherDeleted' : null } |
  { 'enrollmentRemoved' : null } |
  { 'studentUpdated' : null } |
  { 'classUpdated' : null } |
  { 'teacherUpdated' : null } |
  { 'studentCreated' : null } |
  { 'studentDeleted' : null } |
  { 'enrollmentAdded' : null } |
  { 'classCreated' : null } |
  { 'classDeleted' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Class {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'homeroomTeacherId' : [] | [Id],
  'updatedAt' : Timestamp,
  'gradeLevel' : string,
  'capacity' : bigint,
  'enrolledCount' : bigint,
}
export interface ClassDistribution {
  'classId' : Id,
  'className' : string,
  'studentCount' : bigint,
}
export interface ClassFilter {
  'search' : [] | [string],
  'homeroomTeacherId' : [] | [Id],
}
export interface ClassInput {
  'name' : string,
  'homeroomTeacherId' : [] | [Id],
  'gradeLevel' : string,
  'capacity' : bigint,
}
export interface ClassUpdate {
  'name' : [] | [string],
  'homeroomTeacherId' : [] | [Id],
  'gradeLevel' : [] | [string],
  'capacity' : [] | [bigint],
}
export interface DashboardStats {
  'studentsPerClass' : Array<ClassDistribution>,
  'teacherCount' : bigint,
  'classCount' : bigint,
  'studentCount' : bigint,
  'enrollmentCount' : bigint,
}
export interface Enrollment {
  'id' : Id,
  'studentId' : Id,
  'classId' : Id,
  'enrolledAt' : Timestamp,
}
export interface EnrollmentFilter {
  'studentId' : [] | [Id],
  'classId' : [] | [Id],
}
export interface EnrollmentInput { 'studentId' : Id, 'classId' : Id }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Id = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Student {
  'id' : Id,
  'status' : StudentStatus,
  'dateOfBirth' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'guardianPhone' : string,
  'updatedAt' : Timestamp,
  'gender' : Gender,
  'guardianName' : string,
  'classIds' : Array<Id>,
}
export interface StudentFilter {
  'status' : [] | [StudentStatus],
  'search' : [] | [string],
  'classId' : [] | [Id],
}
export interface StudentInput {
  'status' : StudentStatus,
  'dateOfBirth' : string,
  'name' : string,
  'guardianPhone' : string,
  'gender' : Gender,
  'guardianName' : string,
}
export type StudentStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'transferred' : null } |
  { 'graduated' : null };
export interface StudentUpdate {
  'status' : [] | [StudentStatus],
  'dateOfBirth' : [] | [string],
  'name' : [] | [string],
  'guardianPhone' : [] | [string],
  'gender' : [] | [Gender],
  'guardianName' : [] | [string],
}
export interface Teacher {
  'id' : Id,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'phone' : string,
}
export interface TeacherFilter { 'search' : [] | [string] }
export interface TeacherInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface TeacherUpdate {
  'subject' : [] | [string],
  'name' : [] | [string],
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Enroll a student into a class. Admin only.
   */
  'addEnrollment' : ActorMethod<[EnrollmentInput], Enrollment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a class. Admin only.
   */
  'createClass' : ActorMethod<[ClassInput], Class>,
  /**
   * / Create a student. Admin only.
   */
  'createStudent' : ActorMethod<[StudentInput], Student>,
  /**
   * / Create a teacher. Admin only.
   */
  'createTeacher' : ActorMethod<[TeacherInput], Teacher>,
  /**
   * / Delete a class. Admin only.
   */
  'deleteClass' : ActorMethod<[Id], boolean>,
  /**
   * / Delete a student. Admin only.
   */
  'deleteStudent' : ActorMethod<[Id], boolean>,
  /**
   * / Delete a teacher. Admin only.
   */
  'deleteTeacher' : ActorMethod<[Id], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a single class by id.
   */
  'getClass' : ActorMethod<[Id], [] | [Class]>,
  /**
   * / Aggregate counts for the dashboard.
   */
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  /**
   * / Most recent activity entries, newest first.
   */
  'getRecentActivity' : ActorMethod<[bigint], Array<ActivityEntry>>,
  /**
   * / Fetch a single student by id.
   */
  'getStudent' : ActorMethod<[Id], [] | [Student]>,
  /**
   * / Fetch a single teacher by id.
   */
  'getTeacher' : ActorMethod<[Id], [] | [Teacher]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List classes, optionally filtered by search text or homeroom teacher.
   */
  'listClasses' : ActorMethod<[ClassFilter], Array<Class>>,
  /**
   * / List enrollments, optionally filtered by student or class.
   */
  'listEnrollments' : ActorMethod<[EnrollmentFilter], Array<Enrollment>>,
  /**
   * / List students, optionally filtered by search text, class, or status.
   */
  'listStudents' : ActorMethod<[StudentFilter], Array<Student>>,
  /**
   * / List teachers, optionally filtered by search text.
   */
  'listTeachers' : ActorMethod<[TeacherFilter], Array<Teacher>>,
  /**
   * / Remove an enrollment. Admin only.
   */
  'removeEnrollment' : ActorMethod<[Id], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Update a class, including homeroom teacher and capacity. Admin only.
   */
  'updateClass' : ActorMethod<[Id, ClassUpdate], [] | [Class]>,
  /**
   * / Update a student. Admin only.
   */
  'updateStudent' : ActorMethod<[Id, StudentUpdate], [] | [Student]>,
  /**
   * / Update a teacher. Admin only.
   */
  'updateTeacher' : ActorMethod<[Id, TeacherUpdate], [] | [Teacher]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];