/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface ActivityEntry {
    at: Timestamp;
    id: Id;
    kind: ActivityKind;
    message: string;
    performedBy: Principal;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Class {
    id: Id;
    name: string;
    createdAt: Timestamp;
    homeroomTeacherId?: Id;
    updatedAt: Timestamp;
    gradeLevel: string;
    capacity: bigint;
    enrolledCount: bigint;
}
export interface ClassDistribution {
    classId: Id;
    className: string;
    studentCount: bigint;
}
export interface ClassFilter {
    search?: string;
    homeroomTeacherId?: Id;
}
export interface ClassInput {
    name: string;
    homeroomTeacherId?: Id;
    gradeLevel: string;
    capacity: bigint;
}
export interface ClassUpdate {
    name?: string;
    homeroomTeacherId?: Id;
    gradeLevel?: string;
    capacity?: bigint;
}
export interface DashboardStats {
    studentsPerClass: Array<ClassDistribution>;
    teacherCount: bigint;
    classCount: bigint;
    studentCount: bigint;
    enrollmentCount: bigint;
}
export interface Enrollment {
    id: Id;
    studentId: Id;
    classId: Id;
    enrolledAt: Timestamp;
}
export interface EnrollmentFilter {
    studentId?: Id;
    classId?: Id;
}
export interface EnrollmentInput {
    studentId: Id;
    classId: Id;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type Id = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Student {
    id: Id;
    status: StudentStatus;
    dateOfBirth: string;
    name: string;
    createdAt: Timestamp;
    guardianPhone: string;
    updatedAt: Timestamp;
    gender: Gender;
    guardianName: string;
    classIds: Array<Id>;
}
export interface StudentFilter {
    status?: StudentStatus;
    search?: string;
    classId?: Id;
}
export interface StudentInput {
    status: StudentStatus;
    dateOfBirth: string;
    name: string;
    guardianPhone: string;
    gender: Gender;
    guardianName: string;
}
export interface StudentUpdate {
    status?: StudentStatus;
    dateOfBirth?: string;
    name?: string;
    guardianPhone?: string;
    gender?: Gender;
    guardianName?: string;
}
export interface Teacher {
    id: Id;
    subject: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    phone: string;
}
export interface TeacherFilter {
    search?: string;
}
export interface TeacherInput {
    subject: string;
    name: string;
    email: string;
    phone: string;
}
export interface TeacherUpdate {
    subject?: string;
    name?: string;
    email?: string;
    phone?: string;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum ActivityKind {
    teacherCreated = "teacherCreated",
    teacherDeleted = "teacherDeleted",
    enrollmentRemoved = "enrollmentRemoved",
    studentUpdated = "studentUpdated",
    classUpdated = "classUpdated",
    teacherUpdated = "teacherUpdated",
    studentCreated = "studentCreated",
    studentDeleted = "studentDeleted",
    enrollmentAdded = "enrollmentAdded",
    classCreated = "classCreated",
    classDeleted = "classDeleted"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum StudentStatus {
    active = "active",
    inactive = "inactive",
    transferred = "transferred",
    graduated = "graduated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Enroll a student into a class. Admin only.
     */
    addEnrollment(input: EnrollmentInput): Promise<Enrollment>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a class. Admin only.
     */
    createClass(input: ClassInput): Promise<Class>;
    /**
     * / Create a student. Admin only.
     */
    createStudent(input: StudentInput): Promise<Student>;
    /**
     * / Create a teacher. Admin only.
     */
    createTeacher(input: TeacherInput): Promise<Teacher>;
    /**
     * / Delete a class. Admin only.
     */
    deleteClass(id: Id): Promise<boolean>;
    /**
     * / Delete a student. Admin only.
     */
    deleteStudent(id: Id): Promise<boolean>;
    /**
     * / Delete a teacher. Admin only.
     */
    deleteTeacher(id: Id): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the backend API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch a single class by id.
     */
    getClass(id: Id): Promise<Class | null>;
    /**
     * / Aggregate counts for the dashboard.
     */
    getDashboardStats(): Promise<DashboardStats>;
    /**
     * / Most recent activity entries, newest first.
     */
    getRecentActivity(limit: bigint): Promise<Array<ActivityEntry>>;
    /**
     * / Fetch a single student by id.
     */
    getStudent(id: Id): Promise<Student | null>;
    /**
     * / Fetch a single teacher by id.
     */
    getTeacher(id: Id): Promise<Teacher | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List classes, optionally filtered by search text or homeroom teacher.
     */
    listClasses(filter: ClassFilter): Promise<Array<Class>>;
    /**
     * / List enrollments, optionally filtered by student or class.
     */
    listEnrollments(filter: EnrollmentFilter): Promise<Array<Enrollment>>;
    /**
     * / List students, optionally filtered by search text, class, or status.
     */
    listStudents(filter: StudentFilter): Promise<Array<Student>>;
    /**
     * / List teachers, optionally filtered by search text.
     */
    listTeachers(filter: TeacherFilter): Promise<Array<Teacher>>;
    /**
     * / Remove an enrollment. Admin only.
     */
    removeEnrollment(id: Id): Promise<boolean>;
    schema(): Promise<string>;
    /**
     * / Update a class, including homeroom teacher and capacity. Admin only.
     */
    updateClass(id: Id, update: ClassUpdate): Promise<Class | null>;
    /**
     * / Update a student. Admin only.
     */
    updateStudent(id: Id, update: StudentUpdate): Promise<Student | null>;
    /**
     * / Update a teacher. Admin only.
     */
    updateTeacher(id: Id, update: TeacherUpdate): Promise<Teacher | null>;
}
import type { ActivityEntry as _ActivityEntry, ActivityKind as _ActivityKind, Cell as _Cell, Class as _Class, ClassFilter as _ClassFilter, ClassInput as _ClassInput, ClassUpdate as _ClassUpdate, EnrollmentFilter as _EnrollmentFilter, Error as _Error, Gender as _Gender, Id as _Id, Result as _Result, Result__1 as _Result__1, Student as _Student, StudentFilter as _StudentFilter, StudentInput as _StudentInput, StudentStatus as _StudentStatus, StudentUpdate as _StudentUpdate, Teacher as _Teacher, TeacherFilter as _TeacherFilter, TeacherUpdate as _TeacherUpdate, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addEnrollment(arg0: EnrollmentInput): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.addEnrollment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEnrollment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClass(arg0: ClassInput): Promise<Class> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(to_candid_ClassInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Class_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(to_candid_ClassInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Class_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: StudentInput): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(to_candid_StudentInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Student_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(to_candid_StudentInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Student_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTeacher(arg0: TeacherInput): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(arg0);
            return result;
        }
    }
    async deleteClass(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: Id): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getRecentActivity(arg0: bigint): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivity(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivity(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: Id): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: Id): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listClasses(arg0: ClassFilter): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClasses(to_candid_ClassFilter_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClasses(to_candid_ClassFilter_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEnrollments(arg0: EnrollmentFilter): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEnrollments(to_candid_EnrollmentFilter_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEnrollments(to_candid_EnrollmentFilter_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listStudents(arg0: StudentFilter): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents(to_candid_StudentFilter_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents(to_candid_StudentFilter_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeachers(arg0: TeacherFilter): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers(to_candid_TeacherFilter_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers(to_candid_TeacherFilter_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removeEnrollment(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEnrollment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEnrollment(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateClass(arg0: Id, arg1: ClassUpdate): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, to_candid_ClassUpdate_n45(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, to_candid_ClassUpdate_n45(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: Id, arg1: StudentUpdate): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_StudentUpdate_n47(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_StudentUpdate_n47(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTeacher(arg0: Id, arg1: TeacherUpdate): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, to_candid_TeacherUpdate_n49(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, to_candid_TeacherUpdate_n49(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityEntry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEntry): ActivityEntry {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityKind_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityKind): ActivityKind {
    return "teacherCreated" in value ? ActivityKind.teacherCreated : "teacherDeleted" in value ? ActivityKind.teacherDeleted : "enrollmentRemoved" in value ? ActivityKind.enrollmentRemoved : "studentUpdated" in value ? ActivityKind.studentUpdated : "classUpdated" in value ? ActivityKind.classUpdated : "teacherUpdated" in value ? ActivityKind.teacherUpdated : "studentCreated" in value ? ActivityKind.studentCreated : "studentDeleted" in value ? ActivityKind.studentDeleted : "enrollmentAdded" in value ? ActivityKind.enrollmentAdded : "classCreated" in value ? ActivityKind.classCreated : "classDeleted" in value ? ActivityKind.classDeleted : value;
}
function from_candid_Cell_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Class_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Class): Class {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StudentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentStatus): StudentStatus {
    return "active" in value ? StudentStatus.active : "inactive" in value ? StudentStatus.inactive : "transferred" in value ? StudentStatus.transferred : "graduated" in value ? StudentStatus.graduated : value;
}
function from_candid_Student_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Id]): Id | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Class]): Class | null {
    return value.length === 0 ? null : from_candid_Class_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _StudentStatus;
    dateOfBirth: string;
    name: string;
    createdAt: _Timestamp;
    guardianPhone: string;
    updatedAt: _Timestamp;
    gender: _Gender;
    guardianName: string;
    classIds: Array<_Id>;
}): {
    id: Id;
    status: StudentStatus;
    dateOfBirth: string;
    name: string;
    createdAt: Timestamp;
    guardianPhone: string;
    updatedAt: Timestamp;
    gender: Gender;
    guardianName: string;
    classIds: Array<Id>;
} {
    return {
        id: value.id,
        status: from_candid_StudentStatus_n17(_uploadFile, _downloadFile, value.status),
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        createdAt: value.createdAt,
        guardianPhone: value.guardianPhone,
        updatedAt: value.updatedAt,
        gender: from_candid_Gender_n18(_uploadFile, _downloadFile, value.gender),
        guardianName: value.guardianName,
        classIds: value.classIds
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n21(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n25(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    at: _Timestamp;
    id: _Id;
    kind: _ActivityKind;
    message: string;
    performedBy: Principal;
}): {
    at: Timestamp;
    id: Id;
    kind: ActivityKind;
    message: string;
    performedBy: Principal;
} {
    return {
        at: value.at,
        id: value.id,
        kind: from_candid_ActivityKind_n32(_uploadFile, _downloadFile, value.kind),
        message: value.message,
        performedBy: value.performedBy
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    name: string;
    createdAt: _Timestamp;
    homeroomTeacherId: [] | [_Id];
    updatedAt: _Timestamp;
    gradeLevel: string;
    capacity: bigint;
    enrolledCount: bigint;
}): {
    id: Id;
    name: string;
    createdAt: Timestamp;
    homeroomTeacherId?: Id;
    updatedAt: Timestamp;
    gradeLevel: string;
    capacity: bigint;
    enrolledCount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        homeroomTeacherId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.homeroomTeacherId)),
        updatedAt: value.updatedAt,
        gradeLevel: value.gradeLevel,
        capacity: value.capacity,
        enrolledCount: value.enrolledCount
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEntry>): Array<ActivityEntry> {
    return value.map((x)=>from_candid_ActivityEntry_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Class>): Array<Class> {
    return value.map((x)=>from_candid_Class_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n15(_uploadFile, _downloadFile, x));
}
function to_candid_ClassFilter_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassFilter): _ClassFilter {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ClassInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassInput): _ClassInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ClassUpdate_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassUpdate): _ClassUpdate {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_EnrollmentFilter_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnrollmentFilter): _EnrollmentFilter {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_StudentFilter_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentFilter): _StudentFilter {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_StudentInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentInput): _StudentInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_StudentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentStatus): _StudentStatus {
    return value == StudentStatus.active ? {
        active: null
    } : value == StudentStatus.inactive ? {
        inactive: null
    } : value == StudentStatus.transferred ? {
        transferred: null
    } : value == StudentStatus.graduated ? {
        graduated: null
    } : value;
}
function to_candid_StudentUpdate_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentUpdate): _StudentUpdate {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_TeacherFilter_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeacherFilter): _TeacherFilter {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_TeacherUpdate_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeacherUpdate): _TeacherUpdate {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: StudentStatus;
    dateOfBirth: string;
    name: string;
    guardianPhone: string;
    gender: Gender;
    guardianName: string;
}): {
    status: _StudentStatus;
    dateOfBirth: string;
    name: string;
    guardianPhone: string;
    gender: _Gender;
    guardianName: string;
} {
    return {
        status: to_candid_StudentStatus_n13(_uploadFile, _downloadFile, value.status),
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        guardianPhone: value.guardianPhone,
        gender: to_candid_Gender_n14(_uploadFile, _downloadFile, value.gender),
        guardianName: value.guardianName
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    search?: string;
    homeroomTeacherId?: Id;
}): {
    search: [] | [string];
    homeroomTeacherId: [] | [_Id];
} {
    return {
        search: value.search ? candid_some(value.search) : candid_none(),
        homeroomTeacherId: value.homeroomTeacherId ? candid_some(value.homeroomTeacherId) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: Id;
    classId?: Id;
}): {
    studentId: [] | [_Id];
    classId: [] | [_Id];
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        classId: value.classId ? candid_some(value.classId) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: StudentStatus;
    search?: string;
    classId?: Id;
}): {
    status: [] | [_StudentStatus];
    search: [] | [string];
    classId: [] | [_Id];
} {
    return {
        status: value.status ? candid_some(to_candid_StudentStatus_n13(_uploadFile, _downloadFile, value.status)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        classId: value.classId ? candid_some(value.classId) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    search?: string;
}): {
    search: [] | [string];
} {
    return {
        search: value.search ? candid_some(value.search) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    homeroomTeacherId?: Id;
    gradeLevel?: string;
    capacity?: bigint;
}): {
    name: [] | [string];
    homeroomTeacherId: [] | [_Id];
    gradeLevel: [] | [string];
    capacity: [] | [bigint];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        homeroomTeacherId: value.homeroomTeacherId ? candid_some(value.homeroomTeacherId) : candid_none(),
        gradeLevel: value.gradeLevel ? candid_some(value.gradeLevel) : candid_none(),
        capacity: value.capacity ? candid_some(value.capacity) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: StudentStatus;
    dateOfBirth?: string;
    name?: string;
    guardianPhone?: string;
    gender?: Gender;
    guardianName?: string;
}): {
    status: [] | [_StudentStatus];
    dateOfBirth: [] | [string];
    name: [] | [string];
    guardianPhone: [] | [string];
    gender: [] | [_Gender];
    guardianName: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_StudentStatus_n13(_uploadFile, _downloadFile, value.status)) : candid_none(),
        dateOfBirth: value.dateOfBirth ? candid_some(value.dateOfBirth) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        guardianPhone: value.guardianPhone ? candid_some(value.guardianPhone) : candid_none(),
        gender: value.gender ? candid_some(to_candid_Gender_n14(_uploadFile, _downloadFile, value.gender)) : candid_none(),
        guardianName: value.guardianName ? candid_some(value.guardianName) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject?: string;
    name?: string;
    email?: string;
    phone?: string;
}): {
    subject: [] | [string];
    name: [] | [string];
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        subject: value.subject ? candid_some(value.subject) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    homeroomTeacherId?: Id;
    gradeLevel: string;
    capacity: bigint;
}): {
    name: string;
    homeroomTeacherId: [] | [_Id];
    gradeLevel: string;
    capacity: bigint;
} {
    return {
        name: value.name,
        homeroomTeacherId: value.homeroomTeacherId ? candid_some(value.homeroomTeacherId) : candid_none(),
        gradeLevel: value.gradeLevel,
        capacity: value.capacity
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
